version: '3.4'

services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     - SA_PASSWORD=Ye@l!nk0
     - ACCEPT_EULA=Y
    ports:
     - "1440:1433"
  migration:
    image: ${DOCKER_REGISTRY-}migration
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
        - sqldb
